### ISSUE TITLE
windows 下npm run dev 总会出问题

### ISSUE THREAD

**Issue by changdy** [lin-xin/vue-manage-system#103]
首先表示感谢.
目前我们小组内正在以此项目为基础进行开发
但是目前遇到一个问题 项目会莫名其妙的跑不起来.具体表现为
npm run dev 可以正常执行,然后一直卡在 node build/build.js,如果时间久了 我再ctrl c  有可能会报错,报错情况如下:

C:\java_project\rescue-master\client>npm run build

> manage-system@2.1.0 build C:\java_project\rescue-master\client
> node build/build.js

^Cnpm ERR! code ELIFECYCLE
npm ERR! errno 3221225786
npm ERR! manage-system@2.1.0 build: `node build/build.js`
npm ERR! Exit status 3221225786
npm ERR!
npm ERR! Failed at the manage-system@2.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2018-06-18T06_54_34_999Z-debug.log

debug.log 如下:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle manage-system@2.1.0~prebuild: manage-system@2.1.0
6 info lifecycle manage-system@2.1.0~build: manage-system@2.1.0
7 verbose lifecycle manage-system@2.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle manage-system@2.1.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\java_project\rescue-master\client\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;;C:\Users\admin\AppData\Local\Programs\Fiddler;C:\Program Files\Microsoft VS Code\bin;C:\Users\admin\AppData\Roaming\npm;C:\Program Files\Bandizip\
9 verbose lifecycle manage-system@2.1.0~build: CWD: C:\java_project\rescue-master\client
10 silly lifecycle manage-system@2.1.0~build: Args: [ '/d /s /c', 'node build/build.js' ]
11 silly lifecycle manage-system@2.1.0~build: Returned: code: 3221225786  signal: null
12 info lifecycle manage-system@2.1.0~build: Failed to exec build script
13 verbose stack Error: manage-system@2.1.0 build: `node build/build.js`
13 verbose stack Exit status 3221225786
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid manage-system@2.1.0
15 verbose cwd C:\java_project\rescue-master\client
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 3221225786
22 error manage-system@2.1.0 build: `node build/build.js`
22 error Exit status 3221225786
23 error Failed at the manage-system@2.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3221225786, true ]

目前这种情况 不止我一个人电脑上出现,小组同学也有出现过. 但是项目肯定是正常的,因为我在wsl 里面是一切正常的. 
项目环境 node 8.11.1 win10

**Comment by mitboy1983** [comment]
yarn 重装一下模块 然后在 npm run dev
