### ISSUE TITLE
npm run serve后产生的错误

### ISSUE THREAD

**Issue by syloveybx** [lin-xin/vue-manage-system#278]
![image](https://user-images.githubusercontent.com/57025638/113370028-680c9f80-9395-11eb-814e-a15f8543ba3f.png)

**Comment by iluvsnail** [comment]
我也是这个错……

**Comment by FBmm** [comment]
me too!!!!!!

Starting development server...
12% building 18/19 modules 1 active ...ode_modules/eslint-loader/index.js??ref--13-0!/Users/eqxiu/WuqianMac/Project/My/vue-manage-system/src/main.js/Users/eqxiu/WuqianMac/Project/My/vue-manage-system/node_modules/webpack/lib/Dependency.js:239
                throw new Error(
                ^

Error: module property was removed from Dependency (use compilation.moduleGraph.updateModule(dependency, module) instead)
    at ProvidedDependency.set (/Users/eqxiu/WuqianMac/Project/My/vue-manage-system/node_modules/webpack/lib/Dependency.js:239:9)
    at iterationDependencies (/Users/eqxiu/WuqianMac/Project/My/vue-manage-system/node_modules/@vue/cli-service/node_modules/webpack/lib/Compilation.js:940:21)
    at /Users/eqxiu/WuqianMac/Project/My/vue-manage-system/node_modules/@vue/cli-service/node_modules/webpack/lib/Compilation.js:950:8
    at /Users/eqxiu/WuqianMac/Project/My/vue-manage-system/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModuleFactory.js:409:6
    at /Users/eqxiu/WuqianMac/Project/My/vue-manage-system/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModuleFactory.js:155:13
    at eval (eval at create (/Users/eqxiu/WuqianMac/Project/My/vue-manage-system/node_modules/@vue/cli-service/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at /Users/eqxiu/WuqianMac/Project/My/vue-manage-system/node_modules/case-sensitive-paths-webpack-plugin/index.js:178:9
    at /Users/eqxiu/WuqianMac/Project/My/vue-manage-system/node_modules/case-sensitive-paths-webpack-plugin/index.js:125:7
    at /Users/eqxiu/WuqianMac/Project/My/vue-manage-system/node_modules/case-sensitive-paths-webpack-plugin/index.js:125:7
    at CaseSensitivePathsPlugin.fileExistsWithCase (/Users/eqxiu/WuqianMac/Project/My/vue-manage-system/node_modules/case-sensitive-paths-webpack-plugin/index.js:95:5)
    at /Users/eqxiu/WuqianMac/Project/My/vue-manage-system/node_modules/case-sensitive-paths-webpack-plugin/index.js:118:10
    at CaseSensitivePathsPlugin.getFilenamesInDir (/Users/eqxiu/WuqianMac/Project/My/vue-manage-system/node_modules/case-sensitive-paths-webpack-plugin/index.js:52:5)
    at CaseSensitivePathsPlugin.fileExistsWithCase (/Users/eqxiu/WuqianMac/Project/My/vue-manage-system/node_modules/case-sensitive-paths-webpack-plugin/index.js:101:8)
    at /Users/eqxiu/WuqianMac/Project/My/vue-manage-system/node_modules/case-sensitive-paths-webpack-plugin/index.js:118:10
    at Array.<anonymous> (/Users/eqxiu/WuqianMac/Project/My/vue-manage-system/node_modules/case-sensitive-paths-webpack-plugin/index.js:72:5)
    at Storage.finished (/Users/eqxiu/WuqianMac/Project/My/vue-manage-system/node_modules/@vue/cli-service/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)

**Comment by lin-xin** [comment]
这是webpack5兼容的问题。删除掉依赖后，在 package.json 里的devDependencies加上 "webpack": "^4.44.2"，重新安装依赖即可

**Comment by FBmm** [comment]
解决了 作者给力! 以下是步骤：
npm uninstall webpack
npm i -D webpack@4.44.2
npm run serve
