### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by meng250** [lin-xin/vue-manage-system#362]
npm i 后 npm run dev报错
file:///Users/fengmeng/vue-manage-system/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)
    at async link (internal/modules/esm/module_job.js:37:21)

**Comment by willcom95** [comment]
亲测,用npm报错,改用yarn安装依赖可以正常运行
